type
  ptls_handshake_properties_t_anon0_t* = struct_st_ptls_handshake_properties_t_anon0_t
  ptls_handshake_properties_t_anon0_t_client_t* =
    struct_st_ptls_handshake_properties_t_anon0_t_client_t
  ptls_handshake_properties_t_anon0_t_client_t_negotiated_protocols_t* =
    struct_st_ptls_handshake_properties_t_anon0_t_client_t_negotiated_protocols_t
  ptls_handshake_properties_t_anon0_t_client_t_ech_t* =
    struct_st_ptls_handshake_properties_t_anon0_t_client_t_ech_t
  ptls_handshake_properties_t_anon0_t_server_t* =
    struct_st_ptls_handshake_properties_t_anon0_t_server_t
  ptls_handshake_properties_t_anon0_t_server_t_selected_psk_binder_t* =
    struct_st_ptls_handshake_properties_t_anon0_t_server_t_selected_psk_binder_t
  ptls_handshake_properties_t_anon0_t_server_t_cookie_t* =
    struct_st_ptls_handshake_properties_t_anon0_t_server_t_cookie_t
